---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - На сайте должна быть реализована возможность постранично выводить католог товаров
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - Описание и название товара должны соответствовать картинке в карточке товара
  - На сайте должна предоставляться актуальная информация о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - Пользователь должен иметь возможность удалять товар из корзины
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Корзина хранится в сессии браузера
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь не может редактировать карточку товара, его описание, цену
  - На сайте должны быть контакты поддержки, администрации сайта для обратной связи
  - Сайт должен соответствовать требованиям заканодательства страны, в которой он присутствует
