---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, наличию, названию бренда, цвету, категории.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность создать "Личный кабинет" с последующей аутентификацией
  - Пользователь должен иметь возможность удалять товар из корзины
  - Описание и название товара должны соответствовать картинке в карточке товара
  - На сайте должны быть контакты поддержки, администрации сайта для обратной связи
  - На сайте должна предоставляться актуальная информация о товаре
  - Сайт должен соответствовать требованиям заканодательства страны, в которой он присутствует
